function createlegend(axes1)
%CREATELEGEND(AXES1)
%  AXES1:  legend axes

%  Auto-generated by MATLAB on 26-Apr-2017 15:56:03

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.165624950613294 0.786428591069722 0.106250098773411 0.089047618707021],...
    'Interpreter','latex','fontsize',10);

